### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by zmk5**
Sorry, I messed up the rebase. It ended up using my bin files instead of yours. Here is the readme update.

### CODE REVIEW

**Comment by zmk5** [comment]
btw, what is the issue you are running into? Mine builds successfully so far.

**Comment by atyshka** [comment]
Ninja is failing during the compilation because now some C and C++ packages which depend on these messages are using the swift compiler rather than the C compiler. You aren't having this issue? Have you cloned all of the other repos and built from source?

**Comment by zmk5** [comment]
I actually didn't download them and just used sourced the ones installed already on my system. Doing so results in a successful build. Let me try it your way and see what happens.

**Comment by atyshka** [comment]
Yeah that would explain it. Registering the message generator will only apply it to new msg builds, not messages which have already been built and installed. Regarding the issue, my current fix is to explicitly set LINKER_LANGUAGE for each target depending to C/C++/Swift. I filed an issue on rosidl to see if such changes would be accepted in a PR but I'm doubtful they'd like to make such changes across 30+ packages simply to support this library.

**Comment by zmk5** [comment]
That makes sense. I'll see what I can do. One of the reason's I did the objective-C one was it was easier to use incorporate objective-c compiled with Unix Makefiles into a swift project. I still need to work on it more to get it up to snuff. I'll see if basing it off the dotnet one you used may help.

**Comment by atyshka** [comment]
Message gen is working! I got the linker language working with the exception of things using gtest (sensor_msgs and test_msgs). For those I had to fork and add explicit linker language. Eventually I'd like to fix that too but for now this works, I'll see if I can get a PR merged for that. If I have time tomorrow I will update the doc with the necessary changes. Obviously I still have to see if the messages function properly, which requires actually making the client library, but at least it compiles!

**Pull request merged**
